reduce size of test files
conda-forge/nwchem-feedstock pull request #13
Opened 2021-05-19 19:12 UTC by ltalirz

fix #8 

The conda package ships all source files needed for running the tests.
Since the test suite is large (>500MB) we want to ship only those tests
that are actually necessary.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2021-05-19 19:12 UTC, ltalirz commented
@conda-forge-admin, please rerender

2021-05-19 19:12 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-05-19 21:51 UTC, ltalirz commented
@edoapra The tests here failed - could you have a quick look at the files I included and let me know whether any obvious files are missing?

2021-05-19 21:57 UTC, edoapra requested changes
You should have not deleted the line 41 of meta.yml
```
- src/basis/libraries
```

2021-05-19 22:00 UTC, ltalirz commented
> You should have not deleted the line 41 of meta.yml
> 
> ```
> - src/basis/libraries
> ```

The idea was to try to copy it from the installed path, see the change in the `run_tests.sh`

2021-05-19 22:04 UTC, ltalirz commented
Ok, I see now - perhaps the `NWCHEM_BASIS_LIBRARY` environment variable does not take effect here and it is looking for the libraries in a relative path?

That can be fixed; I just add a corresponding symlink

2021-05-20 08:58 UTC, merged

2021-05-20 10:47 UTC, ltalirz commented
I made a minor blunder here by forgetting to bump the build number.

Looking at https://anaconda.org/conda-forge/nwchem/files it seems this means the conda package will not be updated - except for the linux python 3.6 build where the previous build failed on `master` due to some network error (unrelated to our feedstock).

In any case, this is not a big issue - the changes made in this PR will take effect for all versions whenever we bump the build number next (or release e new version).